log_retention_days: 8
temp_directory: d:\work\ArcFolder2\gui_app\temp_archiver
tasks:
  - active: true
    compression: zip_deflated
    days_of_month: []
    days_of_week: []
    destination: D:/!test2
    direct_to_archive: true
    exclude_mask: [сам*]
    include_mask: []
    keep_last: 5
    name: Backup_Task_1
    obj_backup: file
    schedule: daily
    source: D:/!test1
    time: t20:27
    name1c: zzz
    dbname: BuchPro
    loginwin: false
    login1c: 
      Z0FBQUFBQnAzNjQ0bmp4U2ZiWlVLUy1ILVVha05UYVRjNVFUREY0T3dqWElDZXI2MmpWS1M1dnVDckRCSnlHOTlXWWFtVmZhd2V1b0M0U0Npb0ZtWTJIR1pmdk5oV1c4bFE9PQ==
    safe_file: true
    safe_db: false
