log_retention_days: 8
temp_directory: d:\work\ArcFolder2\gui_app\temp_archiver
tasks:
  - active: true
    compression: zip_deflated
    days_of_month: []
    days_of_week: []
    destination: D:/!test2
    direct_to_archive: true
    exclude_mask: []
    include_mask: []
    keep_last: 5
    name: Backup_Task_1
    obj_backup: file
    schedule: daily
    source: D:/!test1
    time: t13:43
    name1c: ''
    dbname: BuchPro
    loginwin: false
    login1c: 
      Z0FBQUFBQnAyTGdUdGl6emtTaDZYSVZSVEwyLWV2Qk4xTXdIOFZkcC1rMElTYmNKOHVXTEQ3clRkdk5jYW9Ja2VYMmJWU29fT0t2ZTRNTlM4RUg1RmE1NlRBQUo1UlB0Wnc9PQ==
