# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QSpinBox, QTabWidget, QTableView,
    QTimeEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QSize(800, 600))
        MainWindow.setMaximumSize(QSize(800, 600))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frm_grid = QFrame(self.centralwidget)
        self.frm_grid.setObjectName(u"frm_grid")
        self.frm_grid.setGeometry(QRect(5, 5, 790, 565))
        self.frm_grid.setAutoFillBackground(True)
        self.frm_grid.setFrameShape(QFrame.Shape.WinPanel)
        self.frm_grid.setFrameShadow(QFrame.Shadow.Raised)
        self.table = QTableView(self.frm_grid)
        self.table.setObjectName(u"table")
        self.table.setGeometry(QRect(8, 8, 776, 546))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(9)
        self.table.setFont(font1)
        self.table.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.frm_edit = QFrame(self.centralwidget)
        self.frm_edit.setObjectName(u"frm_edit")
        self.frm_edit.setGeometry(QRect(5, 5, 790, 565))
        self.frm_edit.setAutoFillBackground(True)
        self.frm_edit.setFrameShape(QFrame.Shape.WinPanel)
        self.frm_edit.setFrameShadow(QFrame.Shadow.Raised)
        self.lbl_name = QLabel(self.frm_edit)
        self.lbl_name.setObjectName(u"lbl_name")
        self.lbl_name.setGeometry(QRect(20, 10, 111, 22))
        self.lbl_name.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_name = QLineEdit(self.frm_edit)
        self.edit_name.setObjectName(u"edit_name")
        self.edit_name.setGeometry(QRect(150, 10, 501, 22))
        self.btn_active = QPushButton(self.frm_edit)
        self.btn_active.setObjectName(u"btn_active")
        self.btn_active.setGeometry(QRect(660, 10, 111, 22))
        self.btn_active.setCheckable(True)
        self.lbl_period = QLabel(self.frm_edit)
        self.lbl_period.setObjectName(u"lbl_period")
        self.lbl_period.setGeometry(QRect(90, 45, 101, 22))
        self.edit_period = QComboBox(self.frm_edit)
        self.edit_period.addItem("")
        self.edit_period.addItem("")
        self.edit_period.addItem("")
        self.edit_period.setObjectName(u"edit_period")
        self.edit_period.setGeometry(QRect(200, 45, 211, 22))
        self.lbl_time = QLabel(self.frm_edit)
        self.lbl_time.setObjectName(u"lbl_time")
        self.lbl_time.setGeometry(QRect(480, 45, 101, 22))
        self.edit_time = QTimeEdit(self.frm_edit)
        self.edit_time.setObjectName(u"edit_time")
        self.edit_time.setGeometry(QRect(590, 45, 71, 22))
        self.tab_period = QTabWidget(self.frm_edit)
        self.tab_period.setObjectName(u"tab_period")
        self.tab_period.setGeometry(QRect(10, 80, 761, 151))
        self.tab_period.setAutoFillBackground(True)
        self.tab_period.setTabShape(QTabWidget.TabShape.Rounded)
        self.tab_day = QWidget()
        self.tab_day.setObjectName(u"tab_day")
        self.tab_day.setAutoFillBackground(True)
        self.frm_day = QFrame(self.tab_day)
        self.frm_day.setObjectName(u"frm_day")
        self.frm_day.setGeometry(QRect(0, 0, 761, 161))
        self.frm_day.setAutoFillBackground(True)
        self.frm_day.setFrameShape(QFrame.Shape.NoFrame)
        self.tab_period.addTab(self.tab_day, "")
        self.tab_week = QWidget()
        self.tab_week.setObjectName(u"tab_week")
        self.tab_week.setAutoFillBackground(True)
        self.frm_week = QFrame(self.tab_week)
        self.frm_week.setObjectName(u"frm_week")
        self.frm_week.setGeometry(QRect(0, 0, 761, 161))
        self.frm_week.setAutoFillBackground(True)
        self.frm_week.setFrameShape(QFrame.Shape.NoFrame)
        self.btn_day_0 = QPushButton(self.frm_week)
        self.btn_day_0.setObjectName(u"btn_day_0")
        self.btn_day_0.setGeometry(QRect(30, 50, 95, 23))
        self.btn_day_0.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_day_0.setCheckable(True)
        self.btn_day_1 = QPushButton(self.frm_week)
        self.btn_day_1.setObjectName(u"btn_day_1")
        self.btn_day_1.setGeometry(QRect(130, 50, 95, 23))
        self.btn_day_1.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_day_1.setCheckable(True)
        self.btn_day_2 = QPushButton(self.frm_week)
        self.btn_day_2.setObjectName(u"btn_day_2")
        self.btn_day_2.setGeometry(QRect(230, 50, 95, 23))
        self.btn_day_2.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_day_2.setCheckable(True)
        self.btn_day_3 = QPushButton(self.frm_week)
        self.btn_day_3.setObjectName(u"btn_day_3")
        self.btn_day_3.setGeometry(QRect(330, 50, 95, 23))
        self.btn_day_3.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_day_3.setCheckable(True)
        self.btn_day_4 = QPushButton(self.frm_week)
        self.btn_day_4.setObjectName(u"btn_day_4")
        self.btn_day_4.setGeometry(QRect(430, 50, 95, 23))
        self.btn_day_4.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_day_4.setCheckable(True)
        self.btn_day_5 = QPushButton(self.frm_week)
        self.btn_day_5.setObjectName(u"btn_day_5")
        self.btn_day_5.setGeometry(QRect(530, 50, 95, 23))
        self.btn_day_5.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_day_5.setCheckable(True)
        self.btn_day_6 = QPushButton(self.frm_week)
        self.btn_day_6.setObjectName(u"btn_day_6")
        self.btn_day_6.setGeometry(QRect(630, 50, 95, 23))
        self.btn_day_6.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_day_6.setCheckable(True)
        self.tab_period.addTab(self.tab_week, "")
        self.tab_month = QWidget()
        self.tab_month.setObjectName(u"tab_month")
        self.tab_month.setAutoFillBackground(True)
        self.frm_month = QFrame(self.tab_month)
        self.frm_month.setObjectName(u"frm_month")
        self.frm_month.setGeometry(QRect(0, 0, 761, 161))
        self.frm_month.setAutoFillBackground(True)
        self.frm_month.setFrameShape(QFrame.Shape.NoFrame)
        self.btn_m_01 = QPushButton(self.frm_month)
        self.btn_m_01.setObjectName(u"btn_m_01")
        self.btn_m_01.setGeometry(QRect(30, 10, 35, 23))
        self.btn_m_01.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_01.setCheckable(True)
        self.btn_m_02 = QPushButton(self.frm_month)
        self.btn_m_02.setObjectName(u"btn_m_02")
        self.btn_m_02.setGeometry(QRect(80, 10, 35, 23))
        self.btn_m_02.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_02.setCheckable(True)
        self.btn_m_03 = QPushButton(self.frm_month)
        self.btn_m_03.setObjectName(u"btn_m_03")
        self.btn_m_03.setGeometry(QRect(130, 10, 35, 23))
        self.btn_m_03.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_03.setCheckable(True)
        self.btn_m_04 = QPushButton(self.frm_month)
        self.btn_m_04.setObjectName(u"btn_m_04")
        self.btn_m_04.setGeometry(QRect(180, 10, 35, 23))
        self.btn_m_04.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_04.setCheckable(True)
        self.btn_m_05 = QPushButton(self.frm_month)
        self.btn_m_05.setObjectName(u"btn_m_05")
        self.btn_m_05.setGeometry(QRect(230, 10, 35, 23))
        self.btn_m_05.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_05.setCheckable(True)
        self.btn_m_06 = QPushButton(self.frm_month)
        self.btn_m_06.setObjectName(u"btn_m_06")
        self.btn_m_06.setGeometry(QRect(280, 10, 35, 23))
        self.btn_m_06.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_06.setCheckable(True)
        self.btn_m_07 = QPushButton(self.frm_month)
        self.btn_m_07.setObjectName(u"btn_m_07")
        self.btn_m_07.setGeometry(QRect(330, 10, 35, 23))
        self.btn_m_07.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_07.setCheckable(True)
        self.btn_m_08 = QPushButton(self.frm_month)
        self.btn_m_08.setObjectName(u"btn_m_08")
        self.btn_m_08.setGeometry(QRect(380, 10, 35, 23))
        self.btn_m_08.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_08.setCheckable(True)
        self.btn_m_09 = QPushButton(self.frm_month)
        self.btn_m_09.setObjectName(u"btn_m_09")
        self.btn_m_09.setGeometry(QRect(430, 10, 35, 23))
        self.btn_m_09.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_09.setCheckable(True)
        self.btn_m_10 = QPushButton(self.frm_month)
        self.btn_m_10.setObjectName(u"btn_m_10")
        self.btn_m_10.setGeometry(QRect(480, 10, 35, 23))
        self.btn_m_10.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_10.setCheckable(True)
        self.btn_m_11 = QPushButton(self.frm_month)
        self.btn_m_11.setObjectName(u"btn_m_11")
        self.btn_m_11.setGeometry(QRect(530, 10, 35, 23))
        self.btn_m_11.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_11.setCheckable(True)
        self.btn_m_12 = QPushButton(self.frm_month)
        self.btn_m_12.setObjectName(u"btn_m_12")
        self.btn_m_12.setGeometry(QRect(580, 10, 35, 23))
        self.btn_m_12.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_12.setCheckable(True)
        self.btn_m_13 = QPushButton(self.frm_month)
        self.btn_m_13.setObjectName(u"btn_m_13")
        self.btn_m_13.setGeometry(QRect(630, 10, 35, 23))
        self.btn_m_13.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_13.setCheckable(True)
        self.btn_m_14 = QPushButton(self.frm_month)
        self.btn_m_14.setObjectName(u"btn_m_14")
        self.btn_m_14.setGeometry(QRect(680, 10, 35, 23))
        self.btn_m_14.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_14.setCheckable(True)
        self.btn_m_15 = QPushButton(self.frm_month)
        self.btn_m_15.setObjectName(u"btn_m_15")
        self.btn_m_15.setGeometry(QRect(30, 50, 35, 23))
        self.btn_m_15.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_15.setCheckable(True)
        self.btn_m_16 = QPushButton(self.frm_month)
        self.btn_m_16.setObjectName(u"btn_m_16")
        self.btn_m_16.setGeometry(QRect(80, 50, 35, 23))
        self.btn_m_16.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_16.setCheckable(True)
        self.btn_m_17 = QPushButton(self.frm_month)
        self.btn_m_17.setObjectName(u"btn_m_17")
        self.btn_m_17.setGeometry(QRect(130, 50, 35, 23))
        self.btn_m_17.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_17.setCheckable(True)
        self.btn_m_18 = QPushButton(self.frm_month)
        self.btn_m_18.setObjectName(u"btn_m_18")
        self.btn_m_18.setGeometry(QRect(180, 50, 35, 23))
        self.btn_m_18.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_18.setCheckable(True)
        self.btn_m_19 = QPushButton(self.frm_month)
        self.btn_m_19.setObjectName(u"btn_m_19")
        self.btn_m_19.setGeometry(QRect(230, 50, 35, 23))
        self.btn_m_19.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_19.setCheckable(True)
        self.btn_m_20 = QPushButton(self.frm_month)
        self.btn_m_20.setObjectName(u"btn_m_20")
        self.btn_m_20.setGeometry(QRect(280, 50, 35, 23))
        self.btn_m_20.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_20.setCheckable(True)
        self.btn_m_21 = QPushButton(self.frm_month)
        self.btn_m_21.setObjectName(u"btn_m_21")
        self.btn_m_21.setGeometry(QRect(330, 50, 35, 23))
        self.btn_m_21.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_21.setCheckable(True)
        self.btn_m_22 = QPushButton(self.frm_month)
        self.btn_m_22.setObjectName(u"btn_m_22")
        self.btn_m_22.setGeometry(QRect(380, 50, 35, 23))
        self.btn_m_22.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_22.setCheckable(True)
        self.btn_m_23 = QPushButton(self.frm_month)
        self.btn_m_23.setObjectName(u"btn_m_23")
        self.btn_m_23.setGeometry(QRect(430, 50, 35, 23))
        self.btn_m_23.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_23.setCheckable(True)
        self.btn_m_24 = QPushButton(self.frm_month)
        self.btn_m_24.setObjectName(u"btn_m_24")
        self.btn_m_24.setGeometry(QRect(480, 50, 35, 23))
        self.btn_m_24.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_24.setCheckable(True)
        self.btn_m_25 = QPushButton(self.frm_month)
        self.btn_m_25.setObjectName(u"btn_m_25")
        self.btn_m_25.setGeometry(QRect(530, 50, 35, 23))
        self.btn_m_25.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_25.setCheckable(True)
        self.btn_m_26 = QPushButton(self.frm_month)
        self.btn_m_26.setObjectName(u"btn_m_26")
        self.btn_m_26.setGeometry(QRect(580, 50, 35, 23))
        self.btn_m_26.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_26.setCheckable(True)
        self.btn_m_27 = QPushButton(self.frm_month)
        self.btn_m_27.setObjectName(u"btn_m_27")
        self.btn_m_27.setGeometry(QRect(630, 50, 35, 23))
        self.btn_m_27.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_27.setCheckable(True)
        self.btn_m_28 = QPushButton(self.frm_month)
        self.btn_m_28.setObjectName(u"btn_m_28")
        self.btn_m_28.setGeometry(QRect(680, 50, 35, 23))
        self.btn_m_28.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_28.setCheckable(True)
        self.btn_m_29 = QPushButton(self.frm_month)
        self.btn_m_29.setObjectName(u"btn_m_29")
        self.btn_m_29.setGeometry(QRect(30, 90, 35, 23))
        self.btn_m_29.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_29.setCheckable(True)
        self.btn_m_30 = QPushButton(self.frm_month)
        self.btn_m_30.setObjectName(u"btn_m_30")
        self.btn_m_30.setGeometry(QRect(80, 90, 35, 23))
        self.btn_m_30.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_30.setCheckable(True)
        self.btn_m_31 = QPushButton(self.frm_month)
        self.btn_m_31.setObjectName(u"btn_m_31")
        self.btn_m_31.setGeometry(QRect(130, 90, 35, 23))
        self.btn_m_31.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_m_31.setCheckable(True)
        self.lbl_mask_incl_2 = QLabel(self.frm_month)
        self.lbl_mask_incl_2.setObjectName(u"lbl_mask_incl_2")
        self.lbl_mask_incl_2.setGeometry(QRect(220, 90, 441, 23))
        self.lbl_mask_incl_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.tab_period.addTab(self.tab_month, "")
        self.lbl_keep_last = QLabel(self.frm_edit)
        self.lbl_keep_last.setObjectName(u"lbl_keep_last")
        self.lbl_keep_last.setGeometry(QRect(20, 460, 311, 20))
        self.lbl_keep_last.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_keep_last = QSpinBox(self.frm_edit)
        self.edit_keep_last.setObjectName(u"edit_keep_last")
        self.edit_keep_last.setGeometry(QRect(340, 460, 51, 20))
        self.edit_keep_last.setMinimum(1)
        self.edit_keep_last.setMaximum(25)
        self.lbl_name_4 = QLabel(self.frm_edit)
        self.lbl_name_4.setObjectName(u"lbl_name_4")
        self.lbl_name_4.setGeometry(QRect(410, 460, 131, 20))
        self.lbl_name_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_compression = QComboBox(self.frm_edit)
        self.edit_compression.addItem("")
        self.edit_compression.addItem("")
        self.edit_compression.setObjectName(u"edit_compression")
        self.edit_compression.setGeometry(QRect(550, 460, 141, 20))
        self.btn_direct_to_archive = QPushButton(self.frm_edit)
        self.btn_direct_to_archive.setObjectName(u"btn_direct_to_archive")
        self.btn_direct_to_archive.setGeometry(QRect(340, 490, 321, 22))
        self.btn_direct_to_archive.setCheckable(True)
        self.lbl_keep_last_3 = QLabel(self.frm_edit)
        self.lbl_keep_last_3.setObjectName(u"lbl_keep_last_3")
        self.lbl_keep_last_3.setGeometry(QRect(20, 490, 311, 22))
        self.lbl_keep_last_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.btn_save = QPushButton(self.frm_edit)
        self.btn_save.setObjectName(u"btn_save")
        self.btn_save.setGeometry(QRect(240, 525, 111, 23))
        self.btn_cancel = QPushButton(self.frm_edit)
        self.btn_cancel.setObjectName(u"btn_cancel")
        self.btn_cancel.setGeometry(QRect(410, 525, 111, 23))
        self.tab_object = QTabWidget(self.frm_edit)
        self.tab_object.setObjectName(u"tab_object")
        self.tab_object.setGeometry(QRect(10, 240, 761, 201))
        self.tab_file = QWidget()
        self.tab_file.setObjectName(u"tab_file")
        self.frm_file = QFrame(self.tab_file)
        self.frm_file.setObjectName(u"frm_file")
        self.frm_file.setGeometry(QRect(-1, 0, 761, 171))
        self.frm_file.setAutoFillBackground(True)
        self.frm_file.setFrameShape(QFrame.Shape.NoFrame)
        self.frm_file.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_name_2 = QLabel(self.frm_file)
        self.lbl_name_2.setObjectName(u"lbl_name_2")
        self.lbl_name_2.setGeometry(QRect(10, 10, 131, 22))
        self.lbl_name_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_source = QLineEdit(self.frm_file)
        self.edit_source.setObjectName(u"edit_source")
        self.edit_source.setGeometry(QRect(150, 10, 561, 22))
        self.edit_source.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.edit_source.setReadOnly(True)
        self.btn_source = QPushButton(self.frm_file)
        self.btn_source.setObjectName(u"btn_source")
        self.btn_source.setGeometry(QRect(710, 10, 31, 22))
        self.lbl_name_3 = QLabel(self.frm_file)
        self.lbl_name_3.setObjectName(u"lbl_name_3")
        self.lbl_name_3.setGeometry(QRect(10, 40, 131, 22))
        self.lbl_name_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.btn_destination = QPushButton(self.frm_file)
        self.btn_destination.setObjectName(u"btn_destination")
        self.btn_destination.setGeometry(QRect(710, 40, 31, 22))
        self.edit_destination = QLineEdit(self.frm_file)
        self.edit_destination.setObjectName(u"edit_destination")
        self.edit_destination.setGeometry(QRect(150, 40, 561, 22))
        self.edit_destination.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.edit_destination.setReadOnly(True)
        self.lbl_mask_incl = QLabel(self.frm_file)
        self.lbl_mask_incl.setObjectName(u"lbl_mask_incl")
        self.lbl_mask_incl.setGeometry(QRect(10, 70, 311, 20))
        self.lbl_mask_incl.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_mask_incl = QLineEdit(self.frm_file)
        self.edit_mask_incl.setObjectName(u"edit_mask_incl")
        self.edit_mask_incl.setGeometry(QRect(330, 70, 411, 22))
        self.lbl_mask_excl = QLabel(self.frm_file)
        self.lbl_mask_excl.setObjectName(u"lbl_mask_excl")
        self.lbl_mask_excl.setGeometry(QRect(10, 100, 311, 20))
        self.lbl_mask_excl.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_mask_excl = QLineEdit(self.frm_file)
        self.edit_mask_excl.setObjectName(u"edit_mask_excl")
        self.edit_mask_excl.setGeometry(QRect(330, 100, 411, 22))
        self.btn_check_mask_incl = QPushButton(self.frm_file)
        self.btn_check_mask_incl.setObjectName(u"btn_check_mask_incl")
        self.btn_check_mask_incl.setGeometry(QRect(630, 70, 111, 20))
        self.btn_check_mask_incl.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_check_mask_excl = QPushButton(self.frm_file)
        self.btn_check_mask_excl.setObjectName(u"btn_check_mask_excl")
        self.btn_check_mask_excl.setGeometry(QRect(630, 100, 111, 22))
        self.btn_check_mask_excl.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_check_mask_incl.raise_()
        self.btn_check_mask_excl.raise_()
        self.lbl_name_2.raise_()
        self.edit_source.raise_()
        self.btn_source.raise_()
        self.lbl_name_3.raise_()
        self.btn_destination.raise_()
        self.edit_destination.raise_()
        self.lbl_mask_incl.raise_()
        self.edit_mask_incl.raise_()
        self.lbl_mask_excl.raise_()
        self.edit_mask_excl.raise_()
        self.tab_object.addTab(self.tab_file, "")
        self.tab_db1c = QWidget()
        self.tab_db1c.setObjectName(u"tab_db1c")
        self.frm_db1c = QFrame(self.tab_db1c)
        self.frm_db1c.setObjectName(u"frm_db1c")
        self.frm_db1c.setGeometry(QRect(0, 0, 761, 171))
        self.frm_db1c.setAutoFillBackground(True)
        self.frm_db1c.setFrameShape(QFrame.Shape.NoFrame)
        self.frm_db1c.setFrameShadow(QFrame.Shadow.Plain)
        self.tab_object.addTab(self.tab_db1c, "")
        self.bottom_bar = QFrame(self.centralwidget)
        self.bottom_bar.setObjectName(u"bottom_bar")
        self.bottom_bar.setGeometry(QRect(4, 572, 790, 25))
        self.bottom_bar.setAutoFillBackground(True)
        self.bottom_bar.setFrameShape(QFrame.Shape.Box)
        self.bottom_bar.setFrameShadow(QFrame.Shadow.Raised)
        self.statusbar = QLabel(self.bottom_bar)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setGeometry(QRect(16, 2, 761, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.frm_grid.raise_()
        self.bottom_bar.raise_()
        self.frm_edit.raise_()
        QWidget.setTabOrder(self.table, self.edit_name)
        QWidget.setTabOrder(self.edit_name, self.btn_active)
        QWidget.setTabOrder(self.btn_active, self.edit_period)
        QWidget.setTabOrder(self.edit_period, self.edit_time)
        QWidget.setTabOrder(self.edit_time, self.tab_period)
        QWidget.setTabOrder(self.tab_period, self.tab_object)
        QWidget.setTabOrder(self.tab_object, self.btn_source)
        QWidget.setTabOrder(self.btn_source, self.btn_destination)
        QWidget.setTabOrder(self.btn_destination, self.edit_mask_incl)
        QWidget.setTabOrder(self.edit_mask_incl, self.edit_mask_excl)
        QWidget.setTabOrder(self.edit_mask_excl, self.edit_keep_last)
        QWidget.setTabOrder(self.edit_keep_last, self.edit_compression)
        QWidget.setTabOrder(self.edit_compression, self.btn_direct_to_archive)
        QWidget.setTabOrder(self.btn_direct_to_archive, self.btn_save)
        QWidget.setTabOrder(self.btn_save, self.btn_cancel)

        self.retranslateUi(MainWindow)

        self.tab_period.setCurrentIndex(0)
        self.tab_object.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ArcFolder", None))
        self.lbl_name.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0437\u0430\u0434\u0430\u0447\u0438", None))
        self.btn_active.setText(QCoreApplication.translate("MainWindow", u"\u0410\u043a\u0442\u0438\u0432\u043d\u0430", None))
        self.lbl_period.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0438\u043e\u0434\u0438\u0447\u043d\u043e\u0441\u0442\u044c", None))
        self.edit_period.setItemText(0, QCoreApplication.translate("MainWindow", u"\u0415\u0436\u0435\u0434\u043d\u0435\u0432\u043d\u043e", None))
        self.edit_period.setItemText(1, QCoreApplication.translate("MainWindow", u"\u0415\u0436\u0435\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u043e", None))
        self.edit_period.setItemText(2, QCoreApplication.translate("MainWindow", u"\u0415\u0436\u0435\u043c\u0435\u0441\u044f\u0447\u043d\u043e", None))

        self.lbl_time.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u043f\u0443\u0441\u043a\u0430", None))
        self.edit_time.setDisplayFormat(QCoreApplication.translate("MainWindow", u"HH:mm", None))
        self.tab_period.setTabText(self.tab_period.indexOf(self.tab_day), QCoreApplication.translate("MainWindow", u"\u0415\u0436\u0435\u0434\u043d\u0435\u0432\u043d\u043e", None))
        self.btn_day_0.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u043a", None))
        self.btn_day_1.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0442\u043e\u0440\u043d\u0438\u043a", None))
        self.btn_day_2.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0440\u0435\u0434\u0430", None))
        self.btn_day_3.setText(QCoreApplication.translate("MainWindow", u"\u0427\u0435\u0442\u0432\u0435\u0440\u0433", None))
        self.btn_day_4.setText(QCoreApplication.translate("MainWindow", u"\u041f\u044f\u0442\u043d\u0438\u0446\u0430", None))
        self.btn_day_5.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0443\u0431\u0431\u043e\u0442\u0430", None))
        self.btn_day_6.setText(QCoreApplication.translate("MainWindow", u"\u0412\u043e\u0441\u043a\u0440\u0435\u0441\u0435\u043d\u044c\u0435", None))
        self.tab_period.setTabText(self.tab_period.indexOf(self.tab_week), QCoreApplication.translate("MainWindow", u"\u0415\u0436\u0435\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u043e", None))
        self.btn_m_01.setText(QCoreApplication.translate("MainWindow", u"01", None))
        self.btn_m_02.setText(QCoreApplication.translate("MainWindow", u"02", None))
        self.btn_m_03.setText(QCoreApplication.translate("MainWindow", u"03", None))
        self.btn_m_04.setText(QCoreApplication.translate("MainWindow", u"04", None))
        self.btn_m_05.setText(QCoreApplication.translate("MainWindow", u"05", None))
        self.btn_m_06.setText(QCoreApplication.translate("MainWindow", u"06", None))
        self.btn_m_07.setText(QCoreApplication.translate("MainWindow", u"07", None))
        self.btn_m_08.setText(QCoreApplication.translate("MainWindow", u"08", None))
        self.btn_m_09.setText(QCoreApplication.translate("MainWindow", u"09", None))
        self.btn_m_10.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.btn_m_11.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.btn_m_12.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.btn_m_13.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.btn_m_14.setText(QCoreApplication.translate("MainWindow", u"14", None))
        self.btn_m_15.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.btn_m_16.setText(QCoreApplication.translate("MainWindow", u"16", None))
        self.btn_m_17.setText(QCoreApplication.translate("MainWindow", u"17", None))
        self.btn_m_18.setText(QCoreApplication.translate("MainWindow", u"18", None))
        self.btn_m_19.setText(QCoreApplication.translate("MainWindow", u"19", None))
        self.btn_m_20.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.btn_m_21.setText(QCoreApplication.translate("MainWindow", u"21", None))
        self.btn_m_22.setText(QCoreApplication.translate("MainWindow", u"22", None))
        self.btn_m_23.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.btn_m_24.setText(QCoreApplication.translate("MainWindow", u"24", None))
        self.btn_m_25.setText(QCoreApplication.translate("MainWindow", u"25", None))
        self.btn_m_26.setText(QCoreApplication.translate("MainWindow", u"26", None))
        self.btn_m_27.setText(QCoreApplication.translate("MainWindow", u"27", None))
        self.btn_m_28.setText(QCoreApplication.translate("MainWindow", u"28", None))
        self.btn_m_29.setText(QCoreApplication.translate("MainWindow", u"29", None))
        self.btn_m_30.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.btn_m_31.setText(QCoreApplication.translate("MainWindow", u"31", None))
        self.lbl_mask_incl_2.setText(QCoreApplication.translate("MainWindow", u"- \u044d\u0442\u0438 \u0447\u0438\u0441\u043b\u0430 \u043f\u0440\u043e\u043f\u0443\u0441\u043a\u0430\u044e\u0442\u0441\u044f \u043f\u0440\u0438 \u043c\u0435\u043d\u044c\u0448\u0435\u043c \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u0435 \u0434\u043d\u0435\u0439 \u0432 \u043c\u0435\u0441\u044f\u0446\u0435", None))
        self.tab_period.setTabText(self.tab_period.indexOf(self.tab_month), QCoreApplication.translate("MainWindow", u"\u0415\u0436\u0435\u043c\u0435\u0441\u044f\u0447\u043d\u043e", None))
        self.lbl_keep_last.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0445\u0440\u0430\u043d\u0438\u043c\u044b\u0445 \u0430\u0440\u0445\u0438\u0432\u043e\u0432 ", None))
        self.lbl_name_4.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0436\u0430\u0442\u0438\u0435 \u0430\u0440\u0445\u0438\u0432\u0430", None))
        self.edit_compression.setItemText(0, QCoreApplication.translate("MainWindow", u"\u0411\u0435\u0437 \u0441\u0436\u0430\u0442\u0438\u044f", None))
        self.edit_compression.setItemText(1, QCoreApplication.translate("MainWindow", u"Zip \u0441\u0436\u0430\u0442\u0438\u0435", None))

        self.btn_direct_to_archive.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u043f\u0440\u044f\u043c\u0443\u044e \u0432 \u0430\u0440\u0445\u0438\u0432", None))
        self.lbl_keep_last_3.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0440\u0435\u043c\u0435\u043d\u043d\u0430\u044f \u043f\u0430\u043f\u043a\u0430 \u0434\u043b\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0430\u0440\u0445\u0438\u0432\u0430", None))
        self.btn_save.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c", None))
        self.btn_cancel.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c", None))
        self.lbl_name_2.setText(QCoreApplication.translate("MainWindow", u"\u0427\u0442\u043e \u043a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u0442\u044c ", None))
        self.btn_source.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_name_3.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0443\u0434\u0430 \u0441\u043e\u0445\u0440\u0430\u043d\u044f\u0442\u044c ", None))
        self.btn_destination.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_mask_incl.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0430\u0441\u043a\u0430 \u0444\u0430\u0439\u043b\u043e\u0432 \u0434\u043b\u044f \u0432\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f \u0432 \u0430\u0440\u0445\u0438\u0432 (\u0447\u0435\u0440\u0435\u0437 , )", None))
        self.lbl_mask_excl.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0430\u0441\u043a\u0430 \u0444\u0430\u0439\u043b\u043e\u0432 \u0434\u043b\u044f \u0438\u0441\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f \u0438\u0437 \u0430\u0440\u0445\u0438\u0432\u0430 (\u0447\u0435\u0440\u0435\u0437 , )", None))
        self.btn_check_mask_incl.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c", None))
        self.btn_check_mask_excl.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c", None))
        self.tab_object.setTabText(self.tab_object.indexOf(self.tab_file), QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0444\u0430\u0439\u043b\u043e\u0432", None))
        self.tab_object.setTabText(self.tab_object.indexOf(self.tab_db1c), QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0431\u0430\u0437\u044b 1\u0441 MS SQL", None))
        self.statusbar.setText("")
    # retranslateUi

